version: '3.8'
services:
  web:
    build:
      context: ./apps/web
      dockerfile: Dockerfile
    env_file: .env
    ports:
      - "3000:3000"
    depends_on:
      - boilerplate-generator
      - webhook
    restart: always

  boilerplate-generator:
    build:
      context: ./apps/boilerplate-generator
      dockerfile: Dockerfile
    env_file: .env
    ports:
      - "4000:4000"
    restart: always

  webhook:
    build:
      context: ./apps/webhook
      dockerfile: Dockerfile
    env_file: .env
    ports:
      - "5000:5000"
    restart: always
